#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

dmdisplay &	# Set default displays and set wallpaper
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Xresources colors/settings
picom &		# picom for transparency
#sxhkd & 		# hotkey daemon
dunst &			# dunst for notifications
setsid -f mopidy &		# mopidy music daemon
setkeyboard &
unclutter --timeout 10 &	# Remove mouse when idle
syndaemon -K -i 0.5 -R -d & 	# Block touchpad while typing
# pulseaudio --start &	# Start pulseaudio

dwmblocks & 	# Start dwm status bar

# Start sync services
nextcloud --background &
onedrive --monitor &

# Fix keyring
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Unlock GPG key
# unlock_pass &

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
# pidof -s runit &&
# 	! pidof -s pulseaudio >/dev/null 2>&1 &&
# 	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
