require('aacienfuegos.lsp.bashls')
require('aacienfuegos.lsp.cmake')
require('aacienfuegos.lsp.css')
require('aacienfuegos.lsp.html')
require('aacienfuegos.lsp.pyright')
require('aacienfuegos.lsp.rust_analyzer')
require('aacienfuegos.lsp.sumneko_lua')
require('aacienfuegos.lsp.tsserver')
